# Generated by Django 4.1.3 on 2022-11-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=6)),
                ('occupation', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'financial_system_user',
                'managed': False,
            },
        ),
    ]
