# Generated by Django 4.1.3 on 2022-11-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0019_remove_beefcowgroupingredients_beef_cow_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeefCowGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('average_meat_output', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ChickenGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('average_meat_output', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='DairyCowGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('average_milk_production', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='GoatGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('average_milk_production', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='PigGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('average_meat_output', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PigGroupIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
                ('pig_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.piggroup')),
            ],
        ),
        migrations.CreateModel(
            name='GoatGroupIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goatgroup')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chicken_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chickengroup')),
                ('dairy_cow_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dairycowgroup')),
                ('goat_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.goatgroup')),
                ('pig_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.piggroup')),
            ],
        ),
        migrations.CreateModel(
            name='DairyCowGroupIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dairy_cow_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dairycowgroup')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ChickenGroupIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chicken_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chickengroup')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='BeefCowGroupIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beef_cow_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.beefcowgroup')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
    ]
